name: Deploy VitePress to GitHub Pages

on:
  push:
    branches:
      - main  # 如果你的主分支是 master，这里也改为 master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run docs:build

      - name: Add CNAME
        run: echo 'bear.js.org' > docs/.vitepress/dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
